name: test to build

on:
    push:
        branches: [ main ]
        
jobs:
    build:
        runs-on: ubunut-latest
        permissions:
            contents: read
            packages: write
            
        steps:
            - mane: Checkout code
              uses: sctions/checkout@v4
              
            - mane: Log in GitHub Conteiner Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secret.GITHUB_TOKEN }}
                
            - mane: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}
                tags: |
                  type=raw,value=latest
                  type=raw,value=v1.0
                                  
            - mane: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}